app.splash = function () {

	'use strict';

	var pub = {
			// generated by http://www.guidgenerator.com/online-guid-generator.aspx
			options : { uuid : '589ad8a6-f527-4540-933b-e2dd2cd9c377' }
		},
		translateTitles;

	pub.onDOMReady = function () {
		console.log('in app.splash.onDOMReady');
		document.getElementById('activityIndicator').hide();
		try {
			blackberry.event.addEventListener('languagechanged', translateTitles);
			translateTitles();
		} catch (e) {
			console.log('addEventListener crashes the app while testing in Ripple');
		}

		app.database = app.databaseUtils.getDatabase();
		//app.ideaDatabase = app.databaseUtils.getIdeaDatabase();
		app.databaseUtils.getData();
		pub.addEventListeners();
	};

	pub.addEventListeners = function () {

		$('#btnIdeaJournal').on('click', function () {
			bb.pushScreen('ideaJournal.html', 'ideaJournal');
		});

		$('#btnScan').on('click', function () {
			bb.pushScreen('scan.html', 'scanScreen');
		});

		$('#btnBBMRegister').on('click', function () {
			console.log('Registering with BBM SP');
			pub.register();
		});

		$('#btnCalendar').on('click', function () {
			bb.pushScreen('calendar.html', 'calendarScreen');
		});

		$('#btnCompass').on('click', function () {
			bb.pushScreen('compass.html', 'compassScreen');
		});


		blackberry.event.addEventListener('swipedown', pub.onSwipedown);
	};

	pub.register = function () {
		if (!app.model.bbmRegistered) {

			try {
				blackberry.event.addEventListener('onaccesschanged', function (accessible, status) {
					document.getElementById('activityIndicator').hide();
					switch (status) {
						case 'allowed' :
							console.log('Access is allowed.');
							app.model.bbmRegistered = true;
							break;
						case 'user' :
							console.log('Access was blocked by the user.');
							break;
						case 'rim' :
							console.log('Access is blocked by RIM');
							break;
						case 'itpolicy' :
							console.log('Access is blocked by IT Policy.');
							break;
						case 'resetrequired' :
							console.log('Access is blocked because a device reset is required to use the BBM Social Platform.');
							break;
						case 'nonuiapp' :
							console.log('Access is blocked because blackberry.bbm.platform.register was called from a non-UI application.');
							break;
						case 'unregistered' :
							console.log('Access is blocked because the application is currently not registered.');
							break;
						case 'pending' :
							console.log('Access is pending and being processed.');
							break;
						case 'nodata' :
							console.log('Access is blocked because the device is out of data coverage. A data connection is required to register the application.');
							break;
						case 'unexpectederror' :
							console.log('Access is blocked because an unexpected error has occured.');
							break;
						case 'invaliduuid' :
							console.log('Access is blocked because an invalid UUID was provided when registering.');
							break;
						case 'temperror' :
							console.log('Access is blocked because of a temporary error. The application should try to call blackberry.bbm.platform.register in 30 minutes, or the next time the application starts.');
							break;
					}

					if (app.model.bbmRegistered) {
						blackberry.ui.toast.show('You are now connected to BBM');
						document.querySelector('#btnBBMRegister').setCaption('BBM Connected');
						document.querySelector('#btnBBMRegister').setImage('assets/icons/bbm.png');
						$('#btnBBMRegister').off('click');

					} else {
						blackberry.ui.toast.show('Attempt to connect to BBM failed.');
					}

				});
				document.getElementById('activityIndicator').show();
				blackberry.ui.toast.show('Connecting to BBM');
				blackberry.bbm.platform.register(pub.options);
			} catch (e) {
				console.log('addEventListener crashes the app while testing in Ripple');
			};
		}
		console.log('app.model.bbmRegistered: ' + app.model.bbmRegistered);
	};

	pub.onScreenPop = function () {
		blackberry.event.removeEventListener('swipedown', pub.onSwipedown);
	};

	pub.onSwipedown = function () {
		try {
			blackberry.ui.dialog.standardAskAsync(
				'Do you really want to refresh the database? All saved locations will be lost!',
				blackberry.ui.dialog.D_YES_NO,
				pub.refreshDatabase,
				{
					title : 'Refresh Database?',
					size : blackberry.ui.dialog.SIZE_MEDIUM,
					position : blackberry.ui.dialog.CENTER
				}
			);
		} catch (e) {
			alert("Exception in standardDialog: " + e);
		}
	};

	pub.refreshDatabase = function (result) {
		if (result.return === "Yes") {
			console.log('drop, recreate and repopulate the location table');
			app.databaseUtils.dropTable(app.database, 'location');
			app.databaseUtils.getData();
		}
	};

	translateTitles = function () {
		var lang = blackberry.system.language,
			stringsObject = app.strings[lang.substring(0, 2)],
			title = 'My Travel Log',
			subTitle = 'Helping you capture your travel memories since 2012';

		if (stringsObject) {
			title = stringsObject.title;
			subTitle = stringsObject.subTitle;
		}

		$('#mainTitle').html(title);
		$('#subTitle').html(subTitle);
	};

	return pub;
}();
